### ISSUE TITLE
Bug so skrytou sadou

### ISSUE THREAD

**Issue by maaario** [trojsten/liahen#16]
1. Si na sade úloh a odhlásiš sa.
2. Admin zmení sadu na skrytú.
3. Nevieš sa prihlásiť

**Comment by ZoltanOnody** [comment]
Problem je tu: https://github.com/trojsten/liahen/blob/8efff3aebb794e300dd3ad17f8f8d853af6ee07c/tasks/views.py#L75

Ak sa to stane, nastavim aktivnu ulohu na `intro:submit`. Nejake pripomienky?
