### ISSUE TITLE
Lokálne spustenie liahne + návod na inštaláciu

### ISSUE THREAD

**Issue by maaario** [trojsten/liahen#2]
Treba si to lokálne rozbehať, vo virtualenv-e, spustiť databázu.

Tiež o tom napísať článok do github wiki. Inšpirujte sa návodom na inštaláciu z trojstenwebu.

Nesubmitovať! kým nemáme development settings, inak by sa to poslalo na testovač a feedback na ostrú liaheň.

Aby sme nemuseli udržiavať externé dependencies iné ako postgresql,
a aby sme nemuseli používať virtuálku,
pri spúštaní liahne odstrnánime Graphviz
`liahen/tasks/views.py::task_set_graph_view` nech teda zostane prázdny

**Comment by ZoltanOnody** [comment]
navod: https://github.com/trojsten/liahen/wiki/In%C5%A1tal%C3%A1cia
