### ISSUE TITLE
Prihlasovanie je rozbite

### ISSUE THREAD

**Issue by maaario** [trojsten/liahen#27]
Asi pri aktualizacii verzii appiek sa rozbilo dropdown menu pri kliknutí na "Prihlásenie"

**Comment by black3r** [comment]
co je na nom rozbite? mas aktualneho mastra? (bol v nom drobny css bug, ktory som fixoval v #24 ale to sa uz merglo)

**Comment by maaario** [comment]
Áno, na mastrovi.

![bug1-liahen](https://cloud.githubusercontent.com/assets/8614957/22925271/576881f4-f2a8-11e6-8ce1-581e00668888.png)

Po klinutí na "ďalšie možnosti prihlásenia".

![bug2-liahen](https://cloud.githubusercontent.com/assets/8614957/22925275/59c86630-f2a8-11e6-89f0-6b644d416b3d.png)

**Comment by black3r** [comment]
mno to vyzera ako ten bug co som fixoval v #24.., a mne to po tom fixe uz funguje.. nemas dajake errory v browsrovej konzole alebo v runserver konzole?

**Comment by maaario** [comment]
Žiadne errory.

Skúsil som si spraviť nový virtualenv a doň naclonovať mastera a stále to robí toto.

**Comment by maaario** [comment]
Ok, asi sa mi neprečistila cache ... funguje to dobre.
